### PR TITLE
Add missing Mechanic tricks

### PR DESCRIPTION
**Pull request by rmorgens**
Add missing Mechanic Tricks, from Armory, Near Space and AP#25.  Update index

### CODE REVIEW

**Comment by LebombJames** [comment]
Do a pull from development, you're nuking some recent changes

**Comment by rmorgens** [comment]
Doing a full audit of Mechanic Tricks to update sourcing, as well as Links, Checks, Ability/Level lookups, embedded rolls.  Level 1 complete.  Levels 8 and 14 still outstanding

**Comment by LebombJames** [comment]
Unfortunately your branch is still nuking development. Some more in-depth messing with git may be in order.

**Comment by rmorgens** [comment]
So, this change shouldn't be touching anything outside Class Features and Starship actions.  Any way to remove the rest of the changes from this PR?

**Comment by LebombJames** [comment]
Could try a rebase, rather than merging from development

**Comment by rmorgens** [comment]
Replaced by PR#1413

**Pull request closed without merging**
