### PR TITLE
Default icons

### PR DESCRIPTION
**Pull request by ian612**
This adds default icons for each actor and item type that get applied automatically in `_preCreate()`.

Once this is merged, I will make an additional PR to alter all the compendium items that still use the default cowled man/bag icon, but only after the outstanding data entry PRs have been completed to prevent conflicts with any that have icons selected.

### CODE REVIEW

**Comment by ian612** [comment]
Here are the icons I've selected, for easy review.

## Items
image
image
image

## Actor
image

**Comment by rmorgens** [comment]
Your Vehicle and Vehicle Attack look better for Mechs when you finish that.  The bus under delapouite looks like a better generic vehicle.  The great-war-tank under cathelineau could be vehicle attack.  Let me know if you need me to forward the specific file and indicate PNG or SVG as preferred

**Comment by ian612** [comment]
Ah yes good point on the mech stuff. Appreciate the suggestion, I'll tweak those ones 🤙

**Review by danimrath — APPROVED** [review]
Looks good to me!

**Pull request merged**
